name: Deploy
on:
  push:
    branches:
      - test

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Update unenv
        run: pnpm update unenv

      - name: Generate Timestamp
        run: pnpm generate:timestamp

      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          cd report && pnpm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
